server:
  port: 8084
spring:
  main:
    bannerMode: off
  application:
    name: loki-logger
  profiles:
    active: dev-test
logging:
#  file:
#    path: logs
  level:
    root: ERROR
    org:
      springframework:
        web: INFO
        servlet:
          DispatcherServlet: ERROR
      hibernate: ERROR
    com:
      ferdousulhaque:
        logger:
          loki: INFO
loki:
  url: http://localhost:3100/loki/api/v1/push
  truncateCount: 100