server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: spring-boot-loki
    static_configs:
      - targets:
          - localhost
        labels:
          app: ${APP_NAME}
          job: spring-boot-loki
          host: ${LOG_HOST}
          __path__: /var/log/*log
